### ISSUE TITLE
Consider velocity while EndDragging.

### ISSUE THREAD

**Issue by imzark** [MaherKSantina/MSPeekCollectionViewDelegateImplementation#53] opened 2019-11-23 15:32 UTC
Act more like isPagingEnabled.

 If the velocity of EndDragging is zero, use "if scrollDistance more than half the page width" to decide destinationIndex, instead of "scrollThreshold". #52 #

**Comment by MaherKSantina** [comment] 2019-12-13 06:25
Hello @imzark , thanks you for raising this issue! I completely re-developed the library using a custom collection view layout and I tried my best to implement your logic with the velocity/scroll threshold. Please take a look and let me know if it behaves as expected. If that's the case feel free to close this issue 👍

**Comment by Sk8er22** [comment] 2019-12-13 09:33
@MaherKSantina Good morning Maher! thanks for your library it's amazing, but in this new version I'm having the following issue http://www.giphy.com/gifs/j45AZB2dGj3FGJvFJH
Any suggestion? ty!

**Comment by MaherKSantina** [comment] 2019-12-13 09:43
Hello @Sk8er22 ! Thank you for your feedback really appreciated! And thank you for raising this issue.

I'm not able to see the gif, I'm getting this error:

<img width="545" alt="Screen Shot 2019-12-13 at 8 42 46 PM" src="https://user-images.githubusercontent.com/24646608/70790424-26936200-1de9-11ea-8a53-97d899118617.png">

**Comment by Sk8er22** [comment] 2019-12-13 09:49
![Dec-13-2019 10-48-58](https://user-images.githubusercontent.com/11601713/70790910-49485b00-1d96-11ea-99f5-a9aa1d0cd7e6.gif)
Done!

**Comment by MaherKSantina** [comment] 2019-12-13 09:57
Ohh that is very bad... I'm sorry you're experiencing this, so let's see how we can fix it. I can't investigate this from the gif as I don't know what's causing this. Are you able to copy the content of the collection view in the example project and see if the issue is still there? This way we can isolate the issue and work on it

**Comment by Sk8er22** [comment] 2019-12-13 10:01
Here is the gif:
![final gif](https://user-images.githubusercontent.com/11601713/70791501-83662c80-1d97-11ea-8d01-8702260937a0.gif)

And the vc:

```
//
//  HomeViewController.swift
//

import Foundation
import MSPeekCollectionViewDelegateImplementation

class HomeViewController: BaseViewController, Storyboarded {
    
    //MVVM
    var viewModel : HomeViewModel!
    
    //UI
    @IBOutlet weak var collectionView: UICollectionView!
    //var delegate: MSPeekCollectionViewDelegateImplementation!
    
    var behavior: MSCollectionViewPeekingBehavior!

    //List of rewards
    
    override func viewDidLoad() {
        super.viewDidLoad()
        bindUI()
        // Register NIB FROM POD
        collectionView.register(LargeDisplayCard.nib, forCellWithReuseIdentifier: "LargeDisplayCard")
        // Required by MSPeekCollectionViewDelegateImplementation
        behavior = MSCollectionViewPeekingBehavior(cellSpacing: 12, cellPeekWidth: 12, scrollDirection: .horizontal)
        collectionView.configureForPeekingBehavior(behavior: behavior)

      //  delegate.delegate = self
        collectionView.delegate = self
        collectionView.dataSource = self
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        // MARK:  Create Navigation bar
        if let navigationController = navigationController {
            navigationController.configureGC(baseViewController: self, hideBackButton: true, title: "".localized(), hideSearch: false, searchAction: nil, hideProfile: false, profileAction: nil)
            //Tab Bar title
            navigationController.title = "Rewards".localized()
        }
    }
    
    func bindUI(){
        //        viewModel.state.rewardsList.subscribe(onNext: { (rewards) in
        //            //What heppen if i get the list before the table
        //        }).disposed(by: disposeBag)
    }
    
    override var preferredStatusBarStyle: UIStatusBarStyle {
        return .lightContent
    }
    
    
}

// MARK: PeekCollectionView
extension HomeViewController: MSPeekImplementationDelegate {
    
    func peekImplementation(_ peekImplementation: MSPeekCollectionViewDelegateImplementation, didChangeActiveIndexTo activeIndex: Int) {
        print("change to \(activeIndex)")
    }
    func peekImplementation(_ peekImplementation: MSPeekCollectionViewDelegateImplementation, didSelectItemAt indexPath: IndexPath) {
        //        if let selectedReward = try? self.viewModel.state.rewardsList.value()[indexPath.row] {
        //            Logg.d(selectedReward)
        //            self.viewModel.event.onNext(RewardsEvent.tapOnFeatured(reward: selectedReward))    }
        //    }
    }
}
extension HomeViewController: UICollectionViewDataSource, UICollectionViewDelegate {
    
    func numberOfSections(in collectionView: UICollectionView) -> Int {
        return 1
    }
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return 5
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "LargeDisplayCard", for: indexPath) as! LargeDisplayCard
        //var cell = Bundle.main.loadNibNamed("LargeDisplayCard", owner: nil, options: nil)?.first as! LargeDisplayCard
        
        cell.imageView.backgroundColor = .lightGray
        cell.overline.text = "API?"
        cell.overline.label.textColor = .primaryActive
        cell.headLine.text = "Complete your first campaign?"
        cell.body.text = "Start your first campaign, a curated group of actions targeting to solve the world's biggest issues.?"
        cell.bottomLabel.text = "2518 Citizens have viewed this story?"
        //        if let rewards = try? viewModel.state.rewardsList.value(){
        //            cell.setupGC(fromReward: rewards[indexPath.row])
        //            cell.dropShadow()
        //        }
        return cell
        
    }
    
    
    func scrollViewWillEndDragging(_ scrollView: UIScrollView, withVelocity velocity: CGPoint, targetContentOffset: UnsafeMutablePointer<CGPoint>) {
            behavior.scrollViewWillEndDragging(scrollView, withVelocity: velocity, targetContentOffset: targetContentOffset)
    }
    
}

```

I'm doing somthing wrong?

Thanks for your fast answer  👍

**Comment by MaherKSantina** [comment] 2019-12-13 10:07
Hello @Sk8er22 , it looks like you're configuring the behavior properly. I can't see any issue from the code you wrote. I'm assuming it's a UI issue where the each cell frame is not computed properly. Are you using a library for the cell items UI? I noticed that when you long press one of them it's becoming smaller, or is it just the selection style?

**Comment by Sk8er22** [comment] 2019-12-13 10:09
Just right now I was trying it commenting the highlighting behavior... but the error persists...

```
import Foundation
import UIKit

public class LargeDisplayCard: UICollectionViewCell, NibLoadable {
    
    @IBOutlet public weak var imageView: UIImageView!
    
    @IBOutlet public weak var overline: Overline!
    @IBOutlet public weak var headLine: RHeadline!
    @IBOutlet public weak var body: SBody!
    @IBOutlet public weak var bottomLabel: UILabel!
    

       override init(frame: CGRect) {
           super.init(frame: frame)
           xibSetup()
       }
    
       required init?(coder aDecoder: NSCoder) {
           super.init(coder: aDecoder)
           xibSetup()
       }
    
       func xibSetup() {
//           view = loadViewFromNib()
//           view.frame = bounds
//           view.autoresizingMask = [.flexibleWidth, .flexibleHeight]
//    
//           addSubview(view)
       }
    func loadViewFromNib() -> UIView {
        let bundle = Bundle(for: type(of: self))
        let nib = UINib(nibName: "LargeDisplayCard", bundle: bundle)
        let view = nib.instantiate(withOwner: self, options: nil).first as! UIView
     
        return view
    }
    
//    override public var isHighlighted: Bool {
//      didSet {
//        UIView.animate(withDuration: 0.5) {
//          let scale: CGFloat = 0.9
//          self.transform = self.isHighlighted ? CGAffineTransform(scaleX: scale, y: scale) : .identity
//        }
//      }
//    }
    
    //Needed to get AUTORESIZED XIB
    override public func preferredLayoutAttributesFitting(_ layoutAttributes: UICollectionViewLayoutAttributes) -> UICollectionViewLayoutAttributes {
        setNeedsLayout()
        layoutIfNeeded()
        let size = contentView.systemLayoutSizeFitting(layoutAttributes.size)
        frame.size.height = ceil(size.height)
        layoutAttributes.frame = frame
        return layoutAttributes
    }
}

```

**Comment by MaherKSantina** [comment] 2019-12-13 10:11
Hmm... so the highlighting is not the issue, and you're not using an external library. Can I bother you to import the collection view code and item UI to the example app and test there? It would be very easy for me to debug the issue if it's in the example project. You can fork the repo and push the UI code and I can pull your branch and investigate it

**Comment by MaherKSantina** [comment] 2019-12-13 10:27
@Sk8er22 thank you soo much for sponsoring me!! 🎉 🎉 🎉 🎉  It really motivates me to pursue my vision and help others with their UI challenges! <3

**Comment by Sk8er22** [comment] 2019-12-13 10:58
The pod with the Large display card is this one... 
https://github.com/levin-riegner/LRDesignSystem
ios 11 on podfile and with the above code my examples should it work

**Comment by MaherKSantina** [comment] 2019-12-13 11:06
Ohh okayy I'll have a try and will let you know how it goes

**Comment by MaherKSantina** [comment] 2019-12-13 11:27
@Sk8er22 I was able to reproduce the issue in the example project! I'll try to investigate and work on a fix now

**Comment by MaherKSantina** [comment] 2019-12-13 11:41
@Sk8er22 I've released a [new version](https://github.com/MaherKSantina/MSPeekCollectionViewDelegateImplementation/releases/tag/3.0.2) of the pod that fixes this issue! Thank you so much for helping me investigate this! I also found another issue related to this but I wanted to push an update for you so you don't have to wait for the other fix. I'll create another ticket for the other issue

Have a good day! 😄

**Comment by Sk8er22** [comment] 2019-12-13 11:44
Thank you so much! :)

**Comment by MaherKSantina** [comment] 2019-12-16 12:11
Hello @imzark , I'm going to close this issue as there has been another thread going on for another issue, but feel free to open a new issue if you noticed that it's not working as intended! Thank you very much for raising this issue and contributing <3

**Closed by MaherKSantina** 2019-12-16 12:11 UTC
